### PR TITLE
run node and tools images as non-root

### LINKED ISSUE #33: Run node/tools images as non-root user
CrossRef: https://github.com/input-output-hk/cardano-node/issues/2584

### PR DESCRIPTION
**Pull request by michaelburch**
fixes #33

I picked up this open item and used your original commit to enable running the node and tools images as a non-root user. The following additions were made:

1. Added "User" field to the dockerTools config to make the non-root user the default
2. Added "Volumes" field to the dockerTools config.  This ensures that data stored in /opt/cardano in the image is copied to any new blank volumes mounted to that path. 

I tested this and confirmed that new volumes are correctly populated with the configs and topology files. I also observed that pre-existing volumes retain the original file ownership of root:root. This could be fixed by running the container as root, fixing permissions and then running su-exec to run entrypoint commands as the non-root user but that seems less appealing. 

I was able to solve this with a one-time fix-up of permissions:

```
docker run --user=0 --rm -it --entrypoint=bash   -v node-data:/opt/cardano/data  nessusio/cardano-node:${CARDANO_NODE_VERSION:-dev} 

bash-4.4# chown -vR 1000:1000 /opt/cardano/
```

Successfully tested with plain docker with data volumes as well as bind mounts, plus with kubernetes.

### CODE REVIEW

**Comment by tdiesler** [comment]
Thanks for looking into this. Could you please squash this to a single commit?
Does this also work with docker compose?
https://github.com/tdiesler/nessus-cardano/blob/main/nix/docker/compose/cardano-node-relay.yaml#L19

**Comment by michaelburch** [comment]
for my previous tests I was mounting a volume for /var/cardano and so I didn't have a permissions error. Found that pretty quickly when testing docker compose. I've fixed it, tested compose, and squashed the commits. 

``
~$ docker ps
CONTAINER ID   IMAGE                       COMMAND                  CREATED              STATUS              PORTS                                       NAMES
3e12e11e3b67   nessusio/cardano-node:dev   "entrypoint run"         About a minute ago   Up About a minute   0.0.0.0:3001->3001/tcp, :::3001->3001/tcp   relay
5fe3f01a425a   nginx                       "/docker-entrypoint.…"   About a minute ago   Up About a minute   0.0.0.0:12798->80/tcp, :::12798->80/tcp     nginx

~$ docker exec 3e12e11e3b67 id
uid=1000(node) gid=1000(node) groups=1000(node)
 
``

**Comment by tdiesler** [comment]
I'm seeing this build error

```
error: a 'x86_64-linux' with features {kvm} is required to 
build '/nix/store/j7gk2zlbmjr6gy0ij620d9xryjqirxpy-docker-layer-cardano-node.drv', 
but I am a 'x86_64-linux' with features {benchmark, big-parallel, nixos-test}
[ERROR] Unable to build image 'nessusio/cardano-node:1.29.0-dev-amd64'
```

We would need to add install instructions for kvm both for x86_64 and arm64

**Comment by michaelburch** [comment]
interesting. looks like the [nix issue 2964](https://github.com/NixOS/nix/issues/2964). I've updated the readme in nix/docker to uncomment this line:

```
system-features = kvm
```

Based an that issue and [this discussion](https://discourse.nixos.org/t/cannot-build-docker-image/7445/5), I think that option bypasses the check for /dev/kvm and will run qemu without nested virtualization support. I update my /etc/nix/nix.conf accordingly. 

I tested this by clearing my docker cache, running nix-collect-garbage, disabling nested virtualization support on my machine, confirmed that /dev/kvm does not exist and re-ran the build. 

Does setting this option in /etc/nix/nix.conf fix the build for you also?

**Comment by tdiesler** [comment]
Ok, the build with system-features=kvm works on my x86_64 machine - still need to verify this on arm64.
In the meanwhile, I suggest to move the additional user setup the base image and remove redundant steps where you can.

You can freely create PRs on https://github.com/tdiesler/nessus-cardano/tree/ghi33 we can squash when done.

cheers

**Comment by tdiesler** [comment]
On my AWS Centos8 aarch64 build instance, I see ...

```
Could not access KVM kernel module: No such file or directory
qemu-system-aarch64: failed to initialize kvm: No such file or directory
builder for '/nix/store/l5ix955ilsmbq6gyrnnxblsm9f3c3dr4-docker-layer-cardano-node.drv' failed with exit code 1
```

What now? Do we know how to install kvm functionality on arm64?

**Comment by tdiesler** [comment]
Closing for now. We don't yet have a solution that works on arm64

**Pull request closed without merging**
