### PR TITLE
CARDANO_BLOCK_PRODUCER should be true for a producer

### PR DESCRIPTION
**Pull request by ASarco**

### CODE REVIEW

**Comment by tdiesler** [comment]
I accepted this PR, but wanted to let you know that `CARDANO_BLOCK_PRODUCER` was set to `false` on purpose. It forces me to think twice before I start a block producer. If the same keys are accidentally still being used on some other host it constitutes a serious offense for which you may get punished in a PoS protokol. For Polkadot for example this is a porcelain offense, which destroys all your stake. With Ethereum you also get `slashed` heavily when you do this (even on accident).

With Cardano, there is no such penalty (yet) AFAIK. Still, it is obviously wrong and if done on purpose indeed a serious offense to have two or more nodes running using the same validator keys.

**Comment by ASarco** [comment]
Oh, I understand. I'm quite new in Cardano and crypto in general, and I thought this was just a mistake.
In that case it'll be good to have a comment briefly explaining this.
BTW thanks for these Docker images, they had saved me a great deal of time!

**Comment by tdiesler** [comment]
UR, welcome

**Comment by ASarco** [comment]
There's seem to be another error (or it might be intentional as well)
The command for starting the producer node includes variables to point to the keys in 
`/var/cardano/config/keys/pool/kes.skey`
But when the keys are copied, they're not copied there:
`docker cp cardano/config/keys tmp:/var/cardano/config/keys`
(there is no pool directory)

**Comment by tdiesler** [comment]
I run this code ...

```
# Remove other/all permissions from private key files
chmod 600 ~/cardano/keys/pool/*

docker volume rm -f cardano-prod-config
docker run --name=tmp -v cardano-prod-config:/var/cardano/config centos
docker cp ~/cardano/config/mainnet-config.json tmp:/var/cardano/config/mainnet-config.json
docker cp ~/cardano/config/mainnet-prod-topology.json tmp:/var/cardano/config/mainnet-topology.json
docker cp ~/cardano/keys tmp:/var/cardano/config/keys
docker rm -f tmp

docker run -it --rm -v cardano-prod-config:/var/cardano/config centos find /var/cardano/config -type f | sort
```

You can always bash into a running container and have a look around like this ...

```
docker exec -it somename bash
```

**Pull request merged**
